name: Build macOS .app

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: write
    env:
      SCHEME: KemonoViewer
    steps:
      - uses: actions/checkout@v4
      - name: Build Swift Package dependencies
        run: |
          cd $SCHEME
          xcodebuild \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk macosx \
            -resolvePackageDependencies
      - name: Archive with clean
        run: |
          cd $SCHEME
          xcodebuild clean archive \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=macOS" \
            -archivePath "$PWD/build/$SCHEME.xcarchive"
      - name: Zip & upload to GitHub Release
        run: |
          cd $SCHEME
          mkdir -p build/extracted
          cp -R build/$SCHEME.xcarchive/Products/Applications/$SCHEME.app build/extracted/
          cd build/extracted
          zip -r "KemonoViewer-macos.zip" "$SCHEME.app"
      - uses: softprops/action-gh-release@v2
        with:
          files: "KemonoViewer/build/extracted/KemonoViewer-macos.zip"
